package multiverse.mars.events;

import multiverse.server.engine.*;
import multiverse.server.network.*;
import multiverse.mars.objects.*;

/**
 * this message means that a player has just completed a quest
 * currently generated by the quest state object
 */
public class QuestCompleted extends MarsEvent {
    public QuestCompleted() {
	super();
    }

    public QuestCompleted(MVByteBuffer buf, ClientConnection con) {
	super(buf,con);
    }

    public QuestCompleted(MarsMob user, MarsQuest quest) {
	super();
	setObject(user);
        setQuestId(quest.getOid());
    }

    @Override
    public String getName() {
	return "QuestCompleted";
    }

    public void setQuestId(Long id) {
        this.questId = id;
    }
    public Long getQuestId() {
        return questId;
    }
    Long questId = null;

    @Override
    public MVByteBuffer toBytes() {
	int msgId = Engine.getEventServer().getEventID(this.getClass());

	MVByteBuffer buf = new MVByteBuffer(20);
	buf.putLong(getObjectOid()); 
	buf.putInt(msgId);
	buf.putLong(getQuestId());
	buf.flip();
	return buf;
    }

    @Override
    protected void parseBytes(MVByteBuffer buf) {
	buf.rewind();
	setObjectOid(buf.getLong());
	/* int msgId = */ buf.getInt();
        setQuestId(buf.getLong());
    }
}